project:
  type: website
  output-dir: docs

website:
  title: "Introduction to data.table"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: material.qmd
        text: Materials
      - href: slides.qmd
        text: Slides

format:
  html:
    theme: 
      - sandstone
      - custom.scss
    mainfont: Commissioner
    monofont: "Fira Code"
    monobackgroundcolor: white
    css: styles.css
    toc: true



